[package]
name = "nadezhda"
version = "0.1.0"
authors = ["Daan van Berkel <daan.v.berkel.1980@gmail.com>"]

[dependencies]
rand = "0.3"

[lib]
name = "nadezhda"
path = "src/lib.rs"

[[bin]]
name = "evolve"
path = "src/bin/evolve.rs"
